### ISSUE TITLE
Allow ability to add accounts

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#103]
#### Account types
- [x] Cash (with sub types)
   - [x] Checking
   - [x] Savings
   - [x] CD
   - [x] Money Market
- [x] Credit Card
- [x] Loan

## Account settings
- [x] Name
- [x] Type
- [x] Balance
- [x] Institution (maybe allow a graphic/logo?)

**Comment by valantur** [comment]
I hope this project develops into a way of tracking net worth over time (multiple accounts and type of accounts, manually entered balances at the end of the month with the option of specifying deposits and withdrawals from those accounts, pretty charts, etc.), instead of transaction-based budgeting like so many other tools.
