### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#14]
# Problem
* People do not understand what this is
* It takes too many brain calories to understand what is going on

# Solution
* Create a detailed README file

Things to talk about:
* What is this project about?
* Why are your working on it?
* Can they contribute?
* How can they follow along?
* How can they run this themselves?

**Comment by danpastori** [comment]
Hi @jaydrogers , I wrote a rough draft of the readme. I probably typed too much as I tend to do and need to clarify. Gives a good idea on how the app works though and what the future should look like.

**Comment by connor11528** [comment]
I think this one can be closed out. One thing that I think is worth mentioning though is that GitHub wiki's can't receive pull requests, so it might make sense to move the wiki content into the main readme or its own `docs` folder. 

I was able to get started with the following:

- Fork and clone repo
- Install Docker for Desktop
- `docker compose up`
- `docker compose -f docker-compose.dev.yml up`

Ran into error:
```
service "meilisearch" has neither an image nor a build context specified: invalid compose project
```
Tried commenting out meilisearch but got the same thing with the next service node.

Tried `docker compose up` which built the Docker containers. Therefore I looked at the volumes (`docker ps -a`) and went into the server (`docker exec -it <container-id> bash`) but there was no code in the `/var/www/html` folder 🤷🏼  I'm guessing I need to run `composer install` and `npm install` somewhere..

I've got Valet running on my local but when I go to http://financial-freedom.test/ I get a PHP error because nothing's built I don't have a `vendor` folder.

```
Warning: require(/Users/connorleech/code/financial-freedom/public/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/connorleech/code/financial-freedom/public/index.php on line 34

Fatal error: require(): Failed opening required '/Users/connorleech/code/financial-freedom/public/../vendor/autoload.php' (include_path='.:/opt/homebrew/Cellar/php@7.4/7.4.28_1/share/php@7.4/pear') in /Users/connorleech/code/financial-freedom/public/index.php on line 34
```

Going to http://financial-freedom.dev.test from the .env file gives me 404.

So what I'm really saying is.. halp! @jaydrogers lol

**Comment by josephmangmang** [comment]
Same here.

**Comment by connor11528** [comment]
I think we just need to run `spin up`. Will give it a go tonight https://serversideup.net/open-source/spin/getting-started/introduction

**Comment by jaydrogers** [comment]
I'll hopefully have some time to improve documentation soon. If not tomorrow, I will be shooting for next Friday (Friday's are my open source days).

I will keep you posted!

**Comment by connor11528** [comment]
Okay I think I figured it out. Had to install [spin](https://serversideup.net/open-source/spin/#run-your-migrations). Then this was specific to me, kill the nginx process I had running on port 80 (`sudo nginx -s stop`).

- Start the environments: `spin up`
- Make sure running the correct version of PHP. On mac `brew install php@8.0 && brew link php@8.0` will suffice.
- Run migrations: `spin exec php php artisan migrate`
- Generate a key: `spin exec php php artisan key:generate`

The spin documentation is great and looks good too! I think I'm all up and running with this now. Would be helpful to have some notes about how to connect to local db and how test DBs work but shouldn't be too hard to figure out :)

**Comment by jaydrogers** [comment]
If you're using `spin`, no need to run `brew install php`.

`spin` will run our Docker containers and get you up and running in a disposable, repeatable environment.

Also, I have things documented here: https://github.com/serversideup/financial-freedom/blob/main/CONTRIBUTING.md

**Comment by connecteev** [comment]
A Readme with installation instructions (with / without Docker) would be excellent. Ideally for both dev and prod.

**Comment by Gitoffomalawn** [comment]
Please also add instructions for those of us that are trying to run this _without_ `spin`. Personally, I feel more comfortable sticking with what I know (`docker` and `docker-compose`), and trying to keep my install as minimal as possible.
